name: CI

on:
    push:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-20.04
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v3
            with:
                python-version: 3.9
          - run: pip install -U pip setuptools wheel twine
          - run: pip install pyflakes black
          - run: pyflakes rest_framework_filters/ tests/
          - run: black rest_framework_filters/ -S --check
    test:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                pyver:
                  - '3.9'
                  - '3.10'
                  - '3.11'
                djver:
                  - '3.1'
                  - '3.2'
                  - '4.0'
                  - '4.1'
                  - '4.2'
        name: Python ${{ matrix.pyver }} Django ${{ matrix.djver }}
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v3
            with:
                python-version: ${{ matrix.pyver }}
          - run: pip install -U pip setuptools wheel twine
          - run: pip install "Django ~= ${{ matrix.djver }}.0" djangorestframework django-filter
          - run: pip install coverage
          - run: pip check
          - run: coverage run --source=rest_framework_filters/ --branch manage.py test
          - run: coverage report --show-missing
    build:
        runs-on: ubuntu-20.04
        needs:
          - lint
          - test
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v3
            with:
                python-version: 3.9
          - run: pip install -U pip setuptools wheel
          - run: pip install build
          - run: pyproject-build .
          - uses: actions/upload-artifact@v3
            with:
                name: distributions
                path: dist/
    upload:
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        runs-on: ubuntu-20.04
        needs:
          - build
        permissions:
            # https://docs.pypi.org/trusted-publishers/using-a-publisher/
            id-token: write
        steps:
          - uses: actions/checkout@v3
          - uses: actions/download-artifact@v3
            with:
                name: distributions
                path: dist/
          - uses: pypa/gh-action-pypi-publish@release/v1
